spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: hjvfirf18
    driverClassName: org.postgresql.Driver
server:
  port: 8080
#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/testIteaWeb
#    username: root
#    password: 5B4#n5u%Pz
#    driverClassName: com.mysql.jdbc.Driver
#server:
#  port: 8080
